### ISSUE TITLE
Auto suggest episode number

### ISSUE THREAD

**Issue by gammaw** [mmmnmnm/lahmacun_arcsi#14]
For example, based on the last know episode number (incremented by one).

**Comment by pvj** [comment]
Yeah, this is UI/UX improvement, I think. 

The `show` object holds all the associated episodes so you could get the last one of them, increment by one, display it in the episode number field as the default value. 

cc @baxgas am I getting this right?

**Comment by gammaw** [comment]
> The show object holds all the associated episodes so you could get the last one of them, increment by one, display it in the episode number field as the default value.

Good idea. I was thinking to remember the lastly added episode's number in the show object (database) but in case you're adding earlier episodes, it's not a good strategy. 

I will look into it.

**Comment by gammaw** [comment]
Last commit implements a simple functionality: if no item number is specified, it looks for the highest existing number and increments it. 

The feature to suggest a number on the form would be a bit trickier because the show selector is on the same form. The proposed feature is simple but it does the job and it helps us well I think. 

The implementation may not be the most elegant one (it goes via the API and JSON-ing). A DB-only solution (via queries) would be certainly possible but this solution was easier for me now and since it doesn't really have a performance implication I just went for it.

**Comment by pvj** [comment]
I get the general idea, and will review the PR shortly. I still think though that this should not be logic on the back-end.

**Comment by gammaw** [comment]
@pvj closed the PR for various reasons: 
- I agree that a server-side implementation must be done via queries. 
- Currently, episode numbers are too chaotic and the increment logic would not be much help. 

I will icebox this issue and open a new one for a simply workaround: https://github.com/mmmnmnm/lahmacun_arcsi/issues/40

**Comment by gammaw** [comment]
Stale + workaround issue exists, closing it.
