### ISSUE TITLE
Server error on listen/download (irregular)

### ISSUE THREAD

**Issue by gammaw** [mmmnmnm/lahmacun_arcsi#25]
@pvj I guess there was no issue for this yet, or was there? Is only listen or download too?

**Comment by gammaw** [comment]
@gammaw yeah it happens for both use cases. 

Just tried for `/item/61/listen` and the result:

![image](https://user-images.githubusercontent.com/28865986/96975883-66ec6200-151b-11eb-9d1c-502df2c24870.png)

And for `/item/61/download` and the result was this: 

![image](https://user-images.githubusercontent.com/28865986/96975954-83889a00-151b-11eb-8a12-7db0a485931d.png)

**Comment by gammaw** [comment]
@pvj I'm sure it's no surprise but here is the root cause so that we have it documented. 

This is the log from `/app/aguni.log` in the arcsi container: 

```
  File "/app/arcsi/api/item.py", line 167, in listen_play_file
    return send_file(
  File "/usr/local/lib/python3.8/site-packages/flask/helpers.py", line 635, in send_file
    fsize = file.getbuffer().nbytes
MemoryError
```

I'm sure that you're ahead of me debugging this. I'll try to help as this seems to be the main blocker of exposing arcsi on the frontend.

**Comment by gammaw** [comment]
Does this help? https://stackoverflow.com/questions/24318084/flask-make-response-with-large-files

**Comment by gammaw** [comment]
Above commit proposes a simple workaround for **download** via redirecting to the generated presigned DO URL. Note that the href can still be the API URL so that it remains persistent (always generates a fresh DO URL), looks nice (in the arcsi domain) and transportable (abstracts DO away). The expert user can see the redirect URL in the response but it shouldn't be a big deal. The pros are obviously that we don't have to download the file inside the app and the storage takes care of parallel users. 

For the **listen** part I could imagine an API which returns the a fresh DO URL and the client can embed it in an audio source HTML. An easy solution can be to do it from PHP but then the URL may expire. Alternatively, Vue (Javascript) can keep the URL fresh.

@pvj what do you think?

**Comment by gammaw** [comment]
> For the listen part I could imagine an API which returns the a fresh DO URL and the client can embed it in an audio source HTML. An easy solution can be to do it from PHP but then the URL may expire. Alternatively, Vue (Javascript) can keep the URL fresh.

Added a small demonstrator for the easy solution via server code (here Flask but could be PHP in Wordpress).

**Comment by gammaw** [comment]
One more addition: the branch is live on dev arcsi, there is no CORS issue there, hopefully there will be no such issue on the front-end side (see https://www.digitalocean.com/docs/spaces/how-to/configure-cors/).

**Comment by pvj** [comment]
Thanks for the write-up and sorry you had to double down on work I've been doing too. I should have shared my findings so we get together ahead faster. 

I came to the same conclusions as you did and started working on the same changes. I vastly underestimated usage of memory for this type of architecture and to be honest it was stupid idea to double to space where we store our data even if temporarily. 

The good thing is that this solution can still work while achieving the goal of the first, namely to hide the original namespaces where we store these files. 

The idea is to keep everything the same code-wise but add a CNAME on our hostrar and then use that URL to create custom domain for our data store at our unnamed selected service provider. Something like media.ourdoma.in?

**Comment by pvj** [comment]
Another small consideration. We would be wise to look out for the filename we use at upload. Since this approach will make us lose the flexibility to set the attachment / file name at client layer.

We will simply serve the file from its source so in order to mask the original filename we need to make sure we don't use that at upload anymore. 

I can take up that task but will make it headache as we either need to bulk rename currently uploaded files or make this backward compatible (and live w/ the fact that some files expose their original filename). Personally I'd go w/ option 1) even if that is more work to be done.

**Comment by gammaw** [comment]
> I came to the same conclusions as you did and started working on the same changes. 

That's a good sign! :)

> The idea is to keep everything the same code-wise as the changes you've deployed to test srv but add a CNAME on our hostrar and then use that URL to create custom domain for our data store at our unnamed selected service provider. Something like media.ourdoma.in?

Good idea, we can definitely look into it. I added an issue for it: https://github.com/mmmnmnm/lahmacun_arcsi/issues/33
I would look at it as an improvement which we wouldn't necessarily need for the first launch. 
With the current solution, we don't show the storage provider for the naive user. The DL link is masked by the API, the player embeds the link (visible through inspect), but I don't think it's catastrophic. 

> Another small consideration. We would be wise to look out for the filename we use at upload. Since this approach will make us lose the flexibility to set the attachment / file name at client layer.

As far as I know the Save as window also shows the original file name so we expose the file name either way, or not? 

> We will simply serve the file from its source so in order to mask the original filename we need to make sure we don't use that at upload anymore.

I'm not sure I get what the issue is (apart from revealing ugly file names which can be taken care of manually until we have automation for it). Do you mean that there may be file name conflicts?

**Comment by pvj** [comment]
>As far as I know the Save as window also shows the original file name so we expose the file name either way, or not?
Yes that is what my question is about. We control how the file is named already, so my question is how to name the files before upload (naming schema) so that once they are D/L'ed they don't expose anything accidentally

>I'm not sure I get what the issue is (apart from revealing ugly file names which can be taken care of manually until we have automation for it). 
We agreed that we should not archive by using the raw filenames.  "until we have automation for it" - we do have that, since we are the API is responsible for uploading the files it receives we have the control over naming.

**Comment by gammaw** [comment]
Oh I see! Now I get it. Do we have an issue for it already? If, not I would open one because it's orthogonal to this one (issue 25).

**Comment by gammaw** [comment]
@pvj will this do? https://github.com/mmmnmnm/lahmacun_arcsi/issues/36

**Comment by gammaw** [comment]
@pvj wrote
![image](https://user-images.githubusercontent.com/28865986/100442723-c7d20180-30a8-11eb-8834-452b85e704b8.png)

I agree that we can/should use the `listen` API for that. And I don't intend to use the `file_url data` in the Python object/JSON response. 

My commit was just a quick demonstrator using the `item` API to show that the original error (server issues through downloading files into arcsi's memory) can be worked around if we use direct DO links (that is why my original commit name was called "Embedded player demonstrator via presigned storage file URL"). Creating a PR using this code may have been premature but since it was working I went for it. But sure, let's do it properly. 

Now the listen API returns a file and not a URL. I didn't find the data structure that I could use to return the file URL that is why I quickly created a new one. If there is a better way, let's do it!

**Comment by gammaw** [comment]
We decided to revert the `file_url` addition and make the `listen` API return the string URL.

**Comment by gammaw** [comment]
@pvj the `listen` API should be fixed now. The `view` didn't work the way we thought it would because the audio source could not resolve the URL based on the arcsi API. So I changed the view code so that it first uses the API to request the URL and passes it for the HTML template. 

https://github.com/mmmnmnm/lahmacun/issues/254 can go ahead using the new listen API.
