### ISSUE TITLE
Edit page should auto-select the original playlist

### ISSUE THREAD

**Issue by gammaw** [mmmnmnm/lahmacun_arcsi#26]
Currently the first show in the list is auto-selected (and override the original if not set otherwise). 

![image](https://user-images.githubusercontent.com/28865986/97432956-0bf0ab80-191d-11eb-8723-73f453809797.png)

**Comment by gammaw** [comment]
@pvj do we need a discussion for that? I guess we need an edit item feature anyway (even if we change a lot on the arcsi GUI) so that this feature request would apply.

**Comment by pvj** [comment]
That's right

**Comment by gammaw** [comment]
Done here ccf7f2577a6e158d221a87c460b9e07d6744f319
