### ISSUE TITLE
Lohuma Azura upload error

### ISSUE THREAD

**Issue by gammaw** [mmmnmnm/lahmacun_arcsi#58]
![image](https://user-images.githubusercontent.com/28865986/106380242-23728100-63b1-11eb-9b0b-5ba7233fb0ed.png)

This happened today. How is it possible that we ever uploaded a Lohuma episode to Azuracast? Maybe we didn't?

**Comment by gammaw** [comment]
Probably it's since we changed the name generation for file uploads. Since then, no Lohuma ep can be uploaded to Azura.

**Comment by pvj** [comment]
Isnt here the problem w/ the fact this is not valid mp3? Filename ends in
part1

**Comment by gammaw** [comment]
The part1 is because it's the first chunk, no? You can see the same ending in the original error: https://github.com/mmmnmnm/lahmacun_arcsi/issues/54#issuecomment-761234391

I'm pretty sure that we didn't try to upload a file with mp3.part1 extension nor the show host sent us such a file.

**Comment by gammaw** [comment]
Done via this: https://github.com/mmmnmnm/lahmacun_arcsi/pull/59
