### ISSUE TITLE
Error while adding new show

### ISSUE THREAD

**Issue by gammaw** [mmmnmnm/lahmacun_arcsi#69]
Cannot add new show, probably since here: https://github.com/mmmnmnm/lahmacun_arcsi/commit/45594d38e60f9006c10858b2f9894f240f861fcd#diff-07f44b067558db42861b61488f3f0d808b24cadc9e6208a650b5242c35dd328b

@pvj can you check? Here the trace:

![image](https://user-images.githubusercontent.com/28865986/110202532-8bf9c580-7e69-11eb-9219-4cf70dafb8a4.png)

**Comment by pvj** [comment]
Working on this on the `more-filenaming` branch

**Comment by gammaw** [comment]
Workaround until this: use the tagged commit https://github.com/mmmnmnm/lahmacun_arcsi/releases/tag/0.1 to add new show (just did it again for a missing show).
