### ISSUE TITLE
Basic uptime monitoring

### ISSUE THREAD

**Issue by pvj** [mmmnmnm/lahmacun_arcsi#71]
We should have simple rules and service to: 
 - look after the health of arcsi
 - inform the team when arcsi is down
 
Nice to have: 
 - log attached or some datetime for context

**Comment by pvj** [comment]
@gammaw Didn't you introduce something that solves this? Or was that for lahma radio only?

**Comment by gammaw** [comment]
Yes, it's for arcsi too. Closing it.
