### ISSUE TITLE
Review log messages and log levels

### ISSUE THREAD

**Issue by pvj** [mmmnmnm/lahmacun_arcsi#72]
We are currently logging too verbose. It is hard to figure out what needs attention and what is just noise, we should aim to reduce this.

**Comment by gammaw** [comment]
Note: all non-app log entries I know of (e.g., `GET` or `Closing connection`) are entered by gunicorn (see for example: https://github.com/benoitc/gunicorn/issues/1952). Related docs: 
https://docs.python.org/3/library/logging.html
https://docs.gunicorn.org/en/stable/settings.html
